name: test
on:
  push:
    branches: [ '**' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@main

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: 🧪 Run Tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@main

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: 🏗️ Build
        run: pnpm build